In [1]:
import numpy as np


#加載數據
def load_data():
    with open('數字01.txt') as fr:
        lines = fr.readlines()

    #最後一列留1,用來計算b
    x = np.ones((len(lines), 13), dtype=float)
    y = np.empty(len(lines), dtype=int)

    for i in range(len(lines)):
        line = lines[i].strip().split(',')
        x[i, :12] = line[:12]
        y[i] = line[12]

    return x, y


x, y = load_data()
x[:5], y[:5]

(array([[1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1.],
        [1., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 0., 1.],
        [1., 1., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1.]]),
 array([0, 0, 0, 0, 0]))

In [2]:
#常量
N, M = x.shape
w = np.empty(13, dtype=float)
w.fill(1 / 13)

In [3]:
#預測函數
def predict(x):
    z = w.dot(x)
    a = 1 / (1 + np.exp(-z))
    return a


predict(x[0]), y[0]

(0.6997597020563492, 0)

In [4]:
#求loss
def get_loss(x, y):
    a = predict(x)
    pred = 1 if a > 0.5 else 0

    #如果預測正確,pred - y為0,則loss為0
    #如果預測錯誤,loss=(pred - y) * a
    return (pred - y) * a


#求總loss
def total_loss():
    _sum = 0
    for i in range(N):
        _sum += get_loss(x[i], y[i])
    return _sum


get_loss(x[0], y[0]), total_loss()

(0.6997597020563492, 21.39089054300221)

In [5]:
def get_gradient(x, y):
    pred = 1 if predict(x) > 0.5 else 0

    #如果預測正確,pred - y為0,則gradient為0
    #如果預測錯誤
    #loss = (pred - y) * w * x
    #d_loss/d_w = (pred - y) * x
    return (pred - y) * x


get_gradient(x[0], y[0])

array([1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1.])

In [6]:
#訓練
for epoch in range(200):
    for i in range(N):
        gred = get_gradient(x[i], y[i])
        w -= gred * 1e-4

    if epoch % 20 == 0:
        print(epoch, total_loss())

0 21.226275985986867
20 17.71212594685117
40 0.5362320220384172
60 0.023755444504269863
80 0.5199281949509837
100 -0.48343803358109694
120 0.5133800297353193
140 0.5099304586338251
160 -0.4934366296775313
180 0.5033807598304969


In [7]:
#測試
correct = 0
for i in range(N):
    pred = 1 if predict(x[i]) > 0.5 else 0

    if pred == y[i]:
        correct += 1

correct / N

0.984375